### ISSUE TITLE
Be able to edit multiple days at once

### ISSUE THREAD

**Issue by phadej** [futurice/hours-ui-cycle#13]
- we should allow editing multiple days at once, i.e. even to "move" on entry from day to another
- but importantly we should indicate that the editing form (only *dirty*? i.e. with entered information) is open somewhere (maybe even have some "goto" button), so people don't forget to press save.

Bonus:
- entry suggestion are updated as *save* buttons are pressed in the forms. Backend could return updated list with each response.

**Comment by janivihervas** [comment]
Implemented:

![screen shot 2016-08-10 at 11 15 29](https://cloud.githubusercontent.com/assets/6649492/17546644/ddba3500-5eeb-11e6-80d4-2327eb747c27.png)

![screen shot 2016-08-10 at 11 15 46](https://cloud.githubusercontent.com/assets/6649492/17546645/ddba996e-5eeb-11e6-9f79-7748d25f9ef4.png)

No "goto" button, but a warning if leaving the site and there are unsaved days.

**Comment by janivihervas** [comment]
Considering: 

> Bonus:
>
> entry suggestion are updated as save buttons are pressed in the forms. Backend could return updated list with each response.

This is also implemented, see https://github.com/futurice/hours-ui-mock-api/blob/master/api/response.go#L19-L23 for response type.

Also UI handles the ACID stuff, because Planmill is entry-based and the UI is day-based with multiple entries, and UI must show if a single entry couldn't be saved, and because backend sends updated project list with every update response. See https://github.com/futurice/hours-ui-cycle/blob/master/src/reducers/api.js#L127-L136
